db_path = "./corrosion.db"

gossip_addr = "[::]:8787"
api_addr = "127.0.0.1:8080"

admin_path = "/var/run/corrosion/admin.sock"

metrics_addr = "127.0.0.1:9090"

bootstrap = []

log_format = "json"

schema_paths = ["/etc/corrosion/schemas"]