[package]
name = "corrosion"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "corrosion"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
backoff = { path = "../backoff" }
bb8 = { workspace = true }
bb8-rusqlite = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
camino = { workspace = true }
compact_str = { workspace = true }
config = { workspace = true }
consul = { path = "../consul" }
exprt = { workspace = true }
eyre = { workspace = true }
fallible-iterator = { workspace = true }
foca = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true }
hyper-rustls = { workspace = true }
jsonschema = { workspace = true }
metrics = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
pgwire = { workspace = true }
quoted-string = { workspace = true }
rand = { workspace = true }
rusqlite = { workspace = true }
rusqlite_migration = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
speedy = { workspace = true }
sqlite3-parser = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tripwire = { path = "../tripwire" }
uhlc = { workspace = true }
uuid = { workspace = true }
webpki = { workspace = true }
lru = { workspace = true }
tokio-util = { version = "0.7.7", features = ["io", "codec", "net"] }
crc32fast = "1.3.2"
tower = { version = "0.4.13", features = ["limit", "load-shed", "buffer"] }
tower-http = { version = "0.4.0", features = ["trace"] }
trust-dns-resolver = "0.22.0"
spawn = { path = "../spawn" }
rangemap = "1.3.0"
corro-types = { path = "../corro-types" }

[dev-dependencies]
tempfile = { workspace = true }
tokio-postgres = { workspace = true }

# [patch.crates-io]
# sqlx = { workspace = true }
