[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "force-frame-pointers",
    "-C", "symbol-mangling-version=v0",
    "-C", "codegen-units=1",
    "-C", "passes=sancov-module",
    "-C", "llvm-args=-sanitizer-coverage-level=3",
    "-C", "llvm-args=-sanitizer-coverage-trace-pc-guard",
    "-C", "link-arg=-Wl,--build-id",
    "-L", "/usr/lib/antithesis/lib/",
    "-l", "voidstar",
    "--cfg", "tokio_unstable"
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "force-frame-pointers",
    "-C", "symbol-mangling-version=v0",
    "--cfg", "tokio_unstable"
]

[target.aarch64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]
