[db]
path = "/var/lib/corrosion/state.db"
schema_paths = ["/app/schemas"]

[gossip]
addr = "fly-local-6pn:8787"
bootstrap = ["corrosion2.internal:8787"]
plaintext = true
max_mtu = 1400

[api]
addr = "[::]:8080"

[admin]
path = "/app/admin.sock"

[telemetry]
prometheus.addr = "0.0.0.0:9090"

[log]
colors = false