[package]
name = "corro-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bb8 = { workspace = true }
bb8-rusqlite = { workspace = true }
camino = { workspace = true }
corro-types = { path = "../corro-types" }
hyper = { workspace = true }
rusqlite = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tokio-tungstenite = { workspace = true }
async-stream = { workspace = true }
tokio = { workspace = true }
pin-project-lite = { workspace = true }
compact_str = { workspace = true }

[features]
