[package]
name = "corro-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
foca = { workspace = true } 
speedy = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
rusqlite = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
bb8 = { workspace = true }
bb8-rusqlite = { workspace = true }
tempfile = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
crc32fast = { workspace = true }
metrics = { workspace = true }
tokio-util = { workspace = true }
thiserror = { workspace = true } 
exprt = { workspace = true }
compact_str = { workspace = true }
uhlc = { workspace = true }
serde_with = { workspace = true }
rangemap = { workspace = true }
camino = { workspace = true }