[package]
name = "corro-types"
version = "0.1.0"
edition = "2021"

[dependencies]
arc-swap = { workspace = true }
async-trait = { workspace = true }
bb8 = { workspace = true }
bb8-rusqlite = { workspace = true }
bytes = { workspace = true }
camino = { workspace = true }
compact_str = { workspace = true }
config = { workspace = true }
consul-client = { path = "../consul-client" }
crc32fast = { workspace = true }
enquote = { workspace = true }
fallible-iterator = { workspace = true }
foca = { workspace = true } 
futures = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
nom = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
rangemap = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
speedy = { workspace = true }
sqlite3-parser = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true } 
time = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uhlc = { workspace = true }
uuid = { workspace = true }