[profile.default]
fail-fast = true
failure-output = "immediate-final"
slow-timeout = { period = "20s", terminate-after = 3 }

[profile.ci]
retries = 5
fail-fast = false
failure-output = "immediate-final"
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci.junit]
path = "junit.xml"
