[test-groups]
serial-integration = { max-threads = 1 }

[profile.default]
fail-fast = true
failure-output = "immediate-final"
slow-timeout = { period = "20s", terminate-after = 3 }

[profile.ci]
retries = 5
fail-fast = false
failure-output = "immediate-final"
slow-timeout = { period = "60s", terminate-after = 2 }

[[profile.ci.overrides]]
filter = 'package(integration-tests)'
test-group = 'serial-integration'
slow-timeout = { period = "120s" }

[profile.ci.junit]
path = "junit.xml"
